CREATE TABLE public."Report" (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
  isEmergency BOOLEAN NOT NULL DEFAULT FALSE,
  userId INTEGER NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user FOREIGN KEY(userId) REFERENCES public."User"(id)
);
